doc:
	pythondoc.py ../util/cert.py ../util/credential.py ../util/gid.py \
                     ../util/rights.py ../util/config.py ../util/hierarchy.py \
                     ../util/record.py ../util/geniclient.py \
                     ../util/geniserver.py 

	pythondoc.py ../registry/registry.py ../registry/import.py \
                     ../registry/nuke.py

	pythondoc.py ../component/component.py
